### ISSUE TITLE
Update not being incorporated into book

### ISSUE THREAD

**Issue by asimonis** [SAEL-SWFSC/SAEL-lab-manual#2]
I updated the Shared Values doc but when I click on the link to the book output, the changes are not being reflected into the lab manual.

**Comment by Kourtney-Burger** [comment]
What updates did you make? I opened it and it seems to be updated as of 5 minutes ago

**Comment by TaikiSan21** [comment]
![image](https://user-images.githubusercontent.com/13296556/198380299-0cc40153-ea4d-4c3f-8960-53682b1e6d0e.png)
I suspect it was still building the page, I checked the changes you made and I believe they are now incorporated. FYI you can tell if GitHub is still working through the Action of building the webpage because you will see a yellow dot next to the action (vs. a green check if completed or red x if it failed).

**Comment by asimonis** [comment]
It's working now. Looks like patience was the solution :-)
